language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.1.400
script: >
  dotnet build -c Release &&
  cd test/MarkdownValidatorTests &&
  dotnet test -c Release --no-build
notifications:
  email: false