sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 2.1.403

script: >
  dotnet build -c Release &&
  cd test/MarkdownValidatorTests &&
  dotnet test -c Release --no-build

notifications:
  email: false